//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetracker.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timetracker.View.Resources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конечная дата не может быть меньше начальной.
        /// </summary>
        public static string API_BadDateCompare {
            get {
                return ResourceManager.GetString("API_BadDateCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка формата даты.
        /// </summary>
        public static string API_BadDateFormat {
            get {
                return ResourceManager.GetString("API_BadDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже приняли приглашение в проект.
        /// </summary>
        public static string API_InviteAccepted {
            get {
                return ResourceManager.GetString("API_InviteAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет доступа.
        /// </summary>
        public static string API_NoAccess {
            get {
                return ResourceManager.GetString("API_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не существует проекта с таким идентификатором.
        /// </summary>
        public static string API_NotExistProjectId {
            get {
                return ResourceManager.GetString("API_NotExistProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не существует пользователя с таким идентификатором.
        /// </summary>
        public static string API_NotExistUserId {
            get {
                return ResourceManager.GetString("API_NotExistUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не существует задачи с таким идентификатором.
        /// </summary>
        public static string API_NotExistWorktaskId {
            get {
                return ResourceManager.GetString("API_NotExistWorktaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не были приглашены в этот проект.
        /// </summary>
        public static string API_YouAreNotInvited {
            get {
                return ResourceManager.GetString("API_YouAreNotInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача была удалена и больше не отслеживается.
        /// </summary>
        public static string SignalR_TaskIsRemoved {
            get {
                return ResourceManager.GetString("SignalR_TaskIsRemoved", resourceCulture);
            }
        }
    }
}
